# Air configuration for Burndler backend development
# Air is a hot reload tool for Go applications

root = "."
tmp_dir = "tmp"

[build]
  # Build command with version injection
  cmd = "go build -ldflags='-X main.Version=dev' -o ../tmp/main ./cmd/api"
  # Binary to execute
  bin = "../tmp/main"
  # Full path to binary
  full_bin = "../tmp/main"
  # Watch these file extensions
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml", "env"]
  # Exclude these directories
  exclude_dir = ["tmp", "vendor", "testdata", "node_modules", ".git", ".idea", ".vscode", "frontend", "dist", "coverage"]
  # Include these directories
  include_dir = ["."]
  # Exclude these files
  exclude_file = []
  # Exclude files with these regex patterns
  exclude_regex = ["_test\\.go$"]
  # Don't build if files haven't changed
  exclude_unchanged = false
  # Follow symbolic links
  follow_symlink = false
  # Delay before restarting (milliseconds)
  delay = 1000
  # Stop on build errors
  stop_on_error = true
  # Log build errors to file
  log = "build-errors.log"

[color]
  # Terminal colors
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[log]
  # Don't add timestamps to logs (backend handles this)
  time = false

[misc]
  # Clean tmp directory on exit
  clean_on_exit = true